<?php

/**
 * @author     Allware Ltda. (http://www.allware.cl)
 * @copyright  2015 Transbank S.A. (http://www.tranbank.cl)
 * @date       Jan 2015
 * @license    GNU LGPL
 * @version    2.0.2
 */

/** Contiene datos de integración para realizar pruebas de conectividad */
return $certificate = array(

    /** Ambiente */
   "environment" => "PRODUCCION",
    /** Llave Privada */
    "private_key" => "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAstkNMrITvyy/aRE+VQ/DRG2U3A58e6T1hBxzFJ/rkyaO/U8C
LRO8W4lw3rpnhqFvSA2M9yN4+oR8beE6tPvrvE2K8+mlev+Gh2YN0RitO0+1J1Nl
nOUKWCEW4G1FC7SHIa4cISM8aLfjS1xD1piksM7Zg9k5AbKqGJk5IaNTCZqBMqFk
ZNNBRNrfjJ8ndi+HoJLEUQbKXYx97KANjhEAu7sc0L1TqXSz6fvXNga9KmuJM5os
AWuYsRpTFSI5IpBzZamtV3GipCrH7ZOSlFQnJ/rWWUEXSYUgB9E5E4oqjow7QpDI
oDUthHlLJlTuGyXWr+AcwWjiuX2mmUGchJownwIDAQABAoIBAHZKz8rvM9Znr3a7
/AFg+qOA40ulnTpewjEObCOBHtxmTX9HycWs3xGgV3JJ0n2euy7qH4m7AaKZDH/U
z/KzCZmzpCtuJ5Cx//YATzU04Cdxsfz/0R6z82KVCD+Kpnd2gUaKlXpphuQwdHr8
3LXMoml7dy0Y+PahiJXaioowL5USaz2naphsF98IPxEjzNL7msIafg3t1mnjZDCk
aQnzk/1L3/NbEN4ztK0kDxlE2h1x4m6cPLHTNV3Ed1PcOaNmJmMkXxrY+GlKxtUM
pOF3b6zVV2O7PpCEj/U06prUA9JAOeme4dKHQQ+HAWsViARzg8N4blR4eo0NzWyJ
AoVIWbECgYEA6OPPK/uHVEXNfAtzvQB8khS2EiepASKzw7szrsm4SoUAuUVr3yNN
jLLi2yOB6QCaS6pMjZRbEmsLj2rMQ5SXlGuvIZ959x/vaMfqKITHZfMRLyZYh7XF
+Z5SSEiZ+OX/VIvX6x+yFb+Fmnu0ZwEgSANk0PmNFO8nG/Aq3qyC5DcCgYEAxJhk
YdwAXunBU7E/7tQSWgYhBoSZqcnyLNGxMtfbEk3bKixyZAJ/LifNlWE86sfqmcnT
iyYnYQINk6GfFQ12aZis+KN3xxhfZYC4kCufz96IsJzBP/lO+M8DDJlQVkjnu18s
4fVeysnDyEcJj/Rf81/IDiXl9LNkTijAqe2MMtkCgYAHX6cgkl8viOI/qjEo68oF
6gf1vTG5qnqcmOHDB/oAygNC2nLW5sw+xy8tlws28GDyQlsYJHlZtO/xw4TiIuNF
vL8Xxm/bJjSzUZkVXVbe4HpLzuAAs/2nsJ6UUVAmtEmISME2XZOK4rx9LquAk2WN
QiZAA5a28feAB/OjhzzBswKBgQC2464++5O8uGmJmlOHsvJ/nUQL9D+fnKcW2tym
F/lNRfClg0PHlisKnSy70wIAyIqPFxsdUBlCPc6zkJ+VzjhidA42IJzFMv9MRjts
o6jAkJ1I8As3oI6/GJYVmmsKWjh6L0hpzQKqVJk2MB/NM+IvXuOVhdwvkNO3gmH5
s2vBwQKBgBfzb7ZQjZ6wPQuQ8se9BDW3GXZavac6AnhQCnIJTDKwffNGiDWgSjZM
/pWShvoD5vX4SydWXVvT8bRVvZkHRO2JUNMKOoAEBVfSpmDi9C1Ns9zoGxL2pKK5
RvbIZeLZ6B/7DR/gufikjKycNgjMwNYauwdDoJYxk2FAxbr9h0q3
-----END RSA PRIVATE KEY-----",

    /** Certificado Publico */
    "public_cert" => "-----BEGIN CERTIFICATE-----
MIIDWjCCAkICCQCGxnejv8aL4jANBgkqhkiG9w0BAQsFADBvMQswCQYDVQQGEwJD
TDETMBEGA1UECAwKU29tZS1TdGF0ZTERMA8GA1UEBwwIU0FOVElBR08xITAfBgNV
BAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEVMBMGA1UEAwwMNTk3MDMzMTgz
NTI2MB4XDTIxMTExNTIwMTkwNVoXDTI1MTExNDIwMTkwNVowbzELMAkGA1UEBhMC
Q0wxEzARBgNVBAgMClNvbWUtU3RhdGUxETAPBgNVBAcMCFNBTlRJQUdPMSEwHwYD
VQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxFTATBgNVBAMMDDU5NzAzMzE4
MzUyNjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALLZDTKyE78sv2kR
PlUPw0RtlNwOfHuk9YQccxSf65Mmjv1PAi0TvFuJcN66Z4ahb0gNjPcjePqEfG3h
OrT767xNivPppXr/hodmDdEYrTtPtSdTZZzlClghFuBtRQu0hyGuHCEjPGi340tc
Q9aYpLDO2YPZOQGyqhiZOSGjUwmagTKhZGTTQUTa34yfJ3Yvh6CSxFEGyl2Mfeyg
DY4RALu7HNC9U6l0s+n71zYGvSpriTOaLAFrmLEaUxUiOSKQc2WprVdxoqQqx+2T
kpRUJyf61llBF0mFIAfROROKKo6MO0KQyKA1LYR5SyZU7hsl1q/gHMFo4rl9pplB
nISaMJ8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAjookxnReGpnaGHLqVGlOzxTF
pwcEDjkYO5EQAiHcJBPHND5r/BsPZ4Z3FeHkrZnLZdLUG2x5YTIzWronFiNdaUy3
ETE7afwAijy5vj7DL23tqEBJSLKDYTxlwczdg0dSUxuplk3Ts5uFXTnO5Pjf5hLj
a81q/LFSNlowIebgOi8pkirlSStGUFN6CAApt9IhWGM3LqXRPIECMCZdj1XhtNnO
LX9DHqxRFEudAa1m2yf3w4jDglXMMMDlK+gBcaIX5E4lgVtQe3gDc/Cf73h/UjyW
NNLjYDHkiANP+YhdPrNQXA3qOMysQtbmfvRuyyrSsWxbzSuPvRpHez5WtIzvsQ==
-----END CERTIFICATE-----",

    /** Certificado Server */
    "webpay_cert" => "-----BEGIN CERTIFICATE-----
MIIDNDCCAhwCCQCJEQxY1moacjANBgkqhkiG9w0BAQsFADBcMQswCQYDVQQGEwJD
TDELMAkGA1UECBMCUk0xETAPBgNVBAcTCFNhbnRpYWdvMRIwEAYDVQQKEwl0cmFu
c2JhbmsxDDAKBgNVBAsTA1BSRDELMAkGA1UEAxMCMTAwHhcNMTQwNTA4MjEwNjIy
WhcNMTgwNTA4MjEwNjIyWjBcMQswCQYDVQQGEwJDTDELMAkGA1UECBMCUk0xETAP
BgNVBAcTCFNhbnRpYWdvMRIwEAYDVQQKEwl0cmFuc2JhbmsxDDAKBgNVBAsTA1BS
RDELMAkGA1UEAxMCMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCk
ag5P6b/BnlpxGk1YX8OeX04ZqmxWThxHP1J+6FVj/hMYw9JGf2gMDCWd3fYaWwRM
X7Y6MidAGCiVwNgsixsUad9C2qQWtpTHoc3T+rQuZ6wmGwxc/K/Gcjf4nuJQUPBo
3zjat+HC0HzPrTscms4A2EZ2VQ/bbznKiOWxcBSqqZ/8jK/RMmu4E6Pzj8Ms+vbA
BfDCq9GDfeNZ+gtQna86enEX7XY/N55SO+VHv/6zGIof7kGIobeF1hYwALrKDhvy
FVQgh4VUBhP0adtnQBfCc1mGVgnviAjioxMxGT4wwaj6IfTvtHhkxVcJ9qmX9oki
wygTooWtcMM6U4oiVd+vAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEqW5DtWdAUP
iSBpExhPgSnm+X6eiDmM3q0S8gWls3hnZCQ9RfhVROj93OS4Zaqg82RLGiU3GsWF
pj4YRw0flCC7bCxo7Mt4Lvv6ihQYdsWxA97HN55HQOVv853kQAu6/vnCxoTtMt6W
+zuiQY7hhabLhOCNJcrFpabj0wCO62IrWv65AZlikcsNKLAwQrstY7Y1VU5DOcXy
FfE5niUGxH0mARXMxq1Z3CBqJ3GKKMmngqCMxX8ZFjIvz0z0VsOJQheX4Hl8prAR
ZlVlkH02xlKKLIO2tcnXik1eW5VCpzuF6z9W3WqcvpaltfspJPx3kN3k5NHATNgk
IypDl0jmq2w=
-----END CERTIFICATE-----",

    /** Codigo Comercio */
    "commerce_code" => "597033183526",

);
